find_path(LIBCLS_ZLOG_CLIENT_INCLUDE_DIR
    rados/cls_zlog_client.h)

find_library(LIBCLS_ZLOG_CLIENT_LIBRARY
    NAMES cls_zlog_client)

mark_as_advanced(LIBCLS_ZLOG_CLIENT_LIBRARY
    LIBCLS_ZLOG_CLIENT_INCLUDE_DIR)

# handle the QUIETLY and REQUIRED arguments and set LIBCLS_ZLOG_CLIENT_FOUND
# to TRUE if all listed variables are TRUE.
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBCLS_ZLOG_CLIENT DEFAULT_MSG
    LIBCLS_ZLOG_CLIENT_LIBRARY LIBCLS_ZLOG_CLIENT_INCLUDE_DIR)

if (LIBCLS_ZLOG_CLIENT_FOUND)
    set(LIBCLS_ZLOG_CLIENT_INCLUDE_DIRS ${LIBCLS_ZLOG_CLIENT_INCLUDE_DIR})
    set(LIBCLS_ZLOG_CLIENT_LIBRARIES ${LIBCLS_ZLOG_CLIENT_LIBRARY})
endif()
